# Change these first
owner: PULSE-Delta # Your GitHub organization or username, where this repository lives
repo: xynostatus # The name of this repository

sites:
  - name: Xyno
    url: https://xyno-network.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.xyno-botlist.tk 
  # baseUrl: /your-repo-name
  name: Status page
  introTitle: "Status page of xyno-Netzwerk"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: "Status of Xyno"
